# prepare-kickstart
---
- hosts: [kickstart]
  remote_user: root
  tasks:
  - name: install the required packages
    # More generic but since we know it is centos
    #   package: name={{ item }} state=latest
    yum: name={{ item }} state=present
    with_items:
    - wget 
    - httpd 
    - tftp 
    - tftp-server 
    - vsftpd 
    - syslinux 
    - ntp 
    - net-tools 
    - bind-utils 
    - tcpdump 
    - pyOpenSSL 
    - git
  - name: disable SELinux
    selinux: policy=targeted state=permissive
  - name: enable and start services
    service: name={{ item }} enabled=yes state=started
    with_items:
    - dnsmasq
    - httpd
    - tftp
    - vsftpd
    - ntpd
