# prepare-kickstart
---
- hosts: [kickstart]
  become: yes

  handlers:
    - name: restart dnsmasq
      service: name=dnsmasq state=restarted
    - name: restart ntp
      service: name=ntpd state=restarted
    - name: restart httpd
      service: name=httpd state=restarted

  tasks:
  - name: install the required packages
    # More generic but since we know it is centos
    #   package: name={{ item }} state=latest
    yum: name={{ item }} state=present
    with_items:
    - wget 
    - httpd 
    - tftp 
    - tftp-server 
    - vsftpd 
    - syslinux 
    - ntp 
    - net-tools 
    - bind-utils 
    - tcpdump 
    - pyOpenSSL 
    - git

  - name: disable SELinux
    selinux: policy=targeted state=permissive

  - name: prepare configuration directories
    file: 
      path: "{{ item }}"
      state: directory
    with_items:
    - /etc/dnsmasq
    - /etc/httpd
    - "{{ tftp_boot_loc }}"
    - "{{ tftp_boot_loc }}/centos_cloud_atomic_23/"

  - name: prepare ISO archives
    file: path={{ archives_loc }} state=directory

  - name: configure dnsmasq
    template: 
      src: "{{ templates_dir }}/dnsmasq.conf.j2" 
      dest: "/etc/dnsmasq/dnsmasq.conf"
      owner: root
      group: root
      mode: 0644
    notify: restart dnsmasq

  - name: configure ntp
    template: 
      src: "{{ templates_dir }}/ntp.conf.j2" 
      dest: "/etc/ntp.conf"
      owner: root
      group: root
      mode: 0644
    notify: restart ntp

  - name: configure httpd
    copy:
      src: "{{ src_cfg_dir }}/etc/httpd/conf.d/local-kickstart.conf" 
      dest: "/etc/httpd/conf.d/local-kickstart.conf"
      owner: root
      group: root
      mode: 0644
    notify: restart httpd

  - name: configure httpd port 8080
    lineinfile:
      dest: "/etc/httpd/conf/httpd.conf"
      regexp: "Listen 8080"
      line: "Listen 8080"
    notify: restart httpd

  - name: enable and start services
    service: name={{ item }} enabled=yes state=started
    with_items:
    - dnsmasq
    - httpd
    - tftp
    - vsftpd
    - ntpd

  - name: add bootloader files
    #synchronize:
    #  src: /usr/share/syslinux
    #  dest: "{{ tftp_boot_loc }}"
    #delegate_to: "{{ inventory_hostname }}"
    copy: >
      remote_src=true
      src=/usr/share/syslinux
      dest={{ tftp_boot_loc }}
    with_fileglob:
      - /usr/share/syslinux/*
    #command: >
    #  cp -r /usr/share/syslinux/ {{ tftp_boot_loc }}

  - name: Setup ISO
    get_url:
      url: "{{ atomic_c_iso_url }}" 
      dest: "{{ atomic_c_iso_loc }}"
      owner: root
      group: root
      mode: 0644

  - name: mount ISOs
    mount: 
      name: /var/ftp/pub/centos_cloud_atomic_23 
      src: "{{ atomic_c_iso_loc }}"
      fstype: auto 
      opts: ro 
      state: mounted

  - name: prepate tftp boot
    copy: >
      remote_src=true
      src={{ item }}
      dest={{ tftp_boot_loc }}/centos_cloud_atomic_23
    with_fileglob:
      - /var/ftp/pub/centos_cloud_atomic_23/images/pxeboot/*

    # command: >
    #   cp /var/ftp/pub/centos_cloud_atomic_23/images/pxeboot/ {{ tftp_boot_loc }}/centos_cloud_atomic_23/

